set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
unbind r
bind r source-file ~/.config/tmux/tmux.conf

set-option -g status-position top


# vim-like pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# mouse support
set -g mouse on

# tmux-sessionizer
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.3'

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_text ' #{?#{==:#{pane_current_command},bash},#{b:pane_current_path},#{pane_current_command}}'
set -g @catppuccin_window_current_text ' #{?#{==:#{pane_current_command},bash},#{b:pane_current_path},#{pane_current_command}}'

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_application}"

run '~/.tmux/plugins/tpm/tpm'
