# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Reinicia o keyd para garantir que a config de Caps↔Esc seja aplicada
exec-once = sudo /usr/bin/systemctl restart keyd

# Inicialização: apps nos workspaces
exec-once = [workspace 1 silent] google-chrome-stable
exec-once = [workspace 2 silent] alacritty
exec-once = [workspace 2 silent] alacritty
exec-once = google-chrome-stable --profile-directory=Default --app-id=ompifgpmddkgmclendfeacglnodjjndh
exec-once = omarchy-launch-webapp https://web.whatsapp.com/
exec-once = [workspace 7 silent] alacritty -e nvim ~/notes
exec-once = [workspace 8 silent] dbeaver
